// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SSMSX
{
    static class Vsix
    {
        public const string Id = "SSMSX.1123e54f-64e7-4ee4-bc5b-bdfec68c52ec";
        public const string Name = "SSMSX";
        public const string Description = "SSMS 2016 Editor Extension project for adding quick fixes to SSMS using MEF";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mister Magoo";
        public const string Tags = "SSMS,Editor,Last,Edit";
    }
}
